export const mockLyrics = [
  { time: 0, text: "(Intro playing...)" },
  { time: 8, text: "Yeah, yeah, yeah" },
  { time: 12, text: "I've been trying to call" },
  { time: 15, text: "I've been on my own for long enough" },
  { time: 19, text: "Maybe you can show me how to love, maybe" },
  { time: 26, text: "I'm going through withdrawals" },
  { time: 29, text: "You don't even have to do too much" },
  { time: 33, text: "You can turn me on with just a touch, baby" },
  { time: 40, text: "I look around and" },
  { time: 43, text: "Sin City's cold and empty (oh)" },
  { time: 47, text: "No one's around to judge me (oh)" },
  { time: 51, text: "I can't see clearly when you're gone" },
  { time: 55, text: "I said, ooh, I'm blinded by the lights" },
  { time: 61, text: "No, I can't sleep until I feel your touch" },
  { time: 69, text: "I said, ooh, I'm drowning in the night" },
  { time: 76, text: "Oh, when I'm like this, you're the one I trust" },
  { time: 83, text: "(Instrumental break)" },
  { time: 92, text: "I'm running out of time" },
  { time: 95, text: "Cause I can see the sun light up the sky" },
  { time: 99, text: "So I hit the road in overdrive, baby, oh" },
  { time: 106, text: "The city's cold and empty (oh)" },
  { time: 110, text: "No one's around to judge me (oh)" },
  { time: 114, text: "I can't see clearly when you're gone" },
  { time: 118, text: "I said, ooh, I'm blinded by the lights" },
  { time: 124, text: "No, I can't sleep until I feel your touch" },
  { time: 133, text: "I said, ooh, I'm drowning in the night" },
  { time: 139, text: "Oh, when I'm like this, you're the one I trust" },
  { time: 147, text: "I'm just walking by to let you know (by to let you know)" },
  { time: 154, text: "I can never say it on the phone (say it on the phone)" },
  { time: 161, text: "Will never let you go this time (ooh)" },
  { time: 172, text: "I said, ooh, I'm blinded by the lights" },
  { time: 179, text: "No, I can't sleep until I feel your touch" },
  { time: 187, text: "Hey, hey, hey" },
  { time: 191, text: "Hey, hey, hey" },
  { time: 195, text: "I said, ooh, I'm blinded by the lights" },
  { time: 201, text: "No, I can't sleep until I feel your touch" },
]
